services:
  service1:
    build: .
    image: bind-alpine 
    ports: [10051:53/tcp, "10051:53/udp"]
    command: [named, -f]
    volumes: ["server1-volume:/etc/bind/"]
    networks:
      bind-network:
        ipv4_address: 192.168.8.11
  service2:
    depends_on: [service1]
    image: bind-alpine 
    ports: [10052:53/tcp, 10052:53/udp]
    command: [named, -f]
    volumes: [server2-volume:/etc/bind/]
    networks:
      bind-network:
        ipv4_address: 192.168.8.22
volumes:
  server1-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./server1-conf
  server2-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./server2-conf
networks:
  bind-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.8.0/24
    